### ISSUE TITLE
Missing mixins

### ISSUE THREAD

**Issue by ConduciveMammal** [CodyHouse/animated-intro-section#1]
Is this repo being maintained?

The scss mixins seems to be missing a few for the various animations such as `cd-reveal-up`

**Comment by sebastiano-guerriero** [comment]
Hi there! It's quite an old repo which uses Bourbon. Prob you didn't import it. We're going through all the repositories to update them all, but it's going to take some time. In the meantime, you can remove the mixins used for the animations, write them as plain CSS and use Autoprefixer if you need to support older browsers.
