### ISSUE TITLE
Change text size of H1 tag and or put whole thing into bootstrap

### ISSUE THREAD

**Issue by haydies01** [CodyHouse/animated-intro-section#2]
Hey! 

Thanks for your work on this. Wondering if you could please advise how I can resize the h1 for the cut theme? Can't seem to change padding or put the h1 with a bootstrap col class to make responsive. Thank you.

**Comment by sebastiano-guerriero** [comment]
Hi there! This resource is not built on any framework, therefore I'm not sure how to make it compatible with Bootstrap. To edit the size of the h1 element, you can either change 

```
.cd-intro-content {
	/* vertically align inside its parent */
	display: table-cell;
	vertical-align: middle;
	/* ... */

	h1 {
		font-size: 2.4rem;
		color: $color-3;
	}
}
```

or target the specific effect:

`.cut.cd-intro-content h1{}`

Cheers
